repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix] # importのソート、未使用削除、PEP8自動修正も全部これでOK

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy

  # Terraform用
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.93.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
