version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    container_name: bedrock_test_app
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspace
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=bedrock_test_db
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /workspace
    user: "1001:1001"
    command: tail -f /dev/null

  mysql:
    image: mysql:8.0
    container_name: bedrock_test_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bedrock_test_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 10s

volumes:
  mysql_data: